# fly.toml app configuration file generated for scouthook-render on 2026-06-25T10:05:38+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scouthook-render'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
