-- Idea Engine: track where a vault_idea originated (document mining vs AI idea engine).
-- Also allow chunk_id to be NULL for idea-engine rows (already SET NULL on delete, just
-- clarifying intent: idea-engine ideas have no source chunk).

ALTER TABLE vault_ideas ADD COLUMN IF NOT EXISTS source VARCHAR(30);
-- 'mined' = extracted from vault document (legacy rows, default)
-- 'idea_engine' = generated by the AI idea engine on the generate page
